//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace NatuurApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/TestDBConnection", ReplyAction="http://tempuri.org/IService1/TestDBConnectionResponse")]
        System.IAsyncResult BeginTestDBConnection(System.AsyncCallback callback, object asyncState);
        
        bool EndTestDBConnection(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetStringResult", ReplyAction="http://tempuri.org/IService1/GetStringResultResponse")]
        System.IAsyncResult BeginGetStringResult(string Query, System.AsyncCallback callback, object asyncState);
        
        string EndGetStringResult(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ExecuteCommand", ReplyAction="http://tempuri.org/IService1/ExecuteCommandResponse")]
        System.IAsyncResult BeginExecuteCommand(string Query, System.AsyncCallback callback, object asyncState);
        
        void EndExecuteCommand(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetDataTable", ReplyAction="http://tempuri.org/IService1/GetDataTableResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
        System.IAsyncResult BeginGetDataTable(string Query, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<object> EndGetDataTable(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : NatuurApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestDBConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TestDBConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStringResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStringResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<object> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<object>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<NatuurApp.ServiceReference1.IService1>, NatuurApp.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginTestDBConnectionDelegate;
        
        private EndOperationDelegate onEndTestDBConnectionDelegate;
        
        private System.Threading.SendOrPostCallback onTestDBConnectionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStringResultDelegate;
        
        private EndOperationDelegate onEndGetStringResultDelegate;
        
        private System.Threading.SendOrPostCallback onGetStringResultCompletedDelegate;
        
        private BeginOperationDelegate onBeginExecuteCommandDelegate;
        
        private EndOperationDelegate onEndExecuteCommandDelegate;
        
        private System.Threading.SendOrPostCallback onExecuteCommandCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDataTableDelegate;
        
        private EndOperationDelegate onEndGetDataTableDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataTableCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<TestDBConnectionCompletedEventArgs> TestDBConnectionCompleted;
        
        public event System.EventHandler<GetStringResultCompletedEventArgs> GetStringResultCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ExecuteCommandCompleted;
        
        public event System.EventHandler<GetDataTableCompletedEventArgs> GetDataTableCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NatuurApp.ServiceReference1.IService1.BeginTestDBConnection(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTestDBConnection(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool NatuurApp.ServiceReference1.IService1.EndTestDBConnection(System.IAsyncResult result) {
            return base.Channel.EndTestDBConnection(result);
        }
        
        private System.IAsyncResult OnBeginTestDBConnection(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((NatuurApp.ServiceReference1.IService1)(this)).BeginTestDBConnection(callback, asyncState);
        }
        
        private object[] OnEndTestDBConnection(System.IAsyncResult result) {
            bool retVal = ((NatuurApp.ServiceReference1.IService1)(this)).EndTestDBConnection(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTestDBConnectionCompleted(object state) {
            if ((this.TestDBConnectionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TestDBConnectionCompleted(this, new TestDBConnectionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TestDBConnectionAsync() {
            this.TestDBConnectionAsync(null);
        }
        
        public void TestDBConnectionAsync(object userState) {
            if ((this.onBeginTestDBConnectionDelegate == null)) {
                this.onBeginTestDBConnectionDelegate = new BeginOperationDelegate(this.OnBeginTestDBConnection);
            }
            if ((this.onEndTestDBConnectionDelegate == null)) {
                this.onEndTestDBConnectionDelegate = new EndOperationDelegate(this.OnEndTestDBConnection);
            }
            if ((this.onTestDBConnectionCompletedDelegate == null)) {
                this.onTestDBConnectionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTestDBConnectionCompleted);
            }
            base.InvokeAsync(this.onBeginTestDBConnectionDelegate, null, this.onEndTestDBConnectionDelegate, this.onTestDBConnectionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NatuurApp.ServiceReference1.IService1.BeginGetStringResult(string Query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStringResult(Query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string NatuurApp.ServiceReference1.IService1.EndGetStringResult(System.IAsyncResult result) {
            return base.Channel.EndGetStringResult(result);
        }
        
        private System.IAsyncResult OnBeginGetStringResult(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Query = ((string)(inValues[0]));
            return ((NatuurApp.ServiceReference1.IService1)(this)).BeginGetStringResult(Query, callback, asyncState);
        }
        
        private object[] OnEndGetStringResult(System.IAsyncResult result) {
            string retVal = ((NatuurApp.ServiceReference1.IService1)(this)).EndGetStringResult(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStringResultCompleted(object state) {
            if ((this.GetStringResultCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStringResultCompleted(this, new GetStringResultCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStringResultAsync(string Query) {
            this.GetStringResultAsync(Query, null);
        }
        
        public void GetStringResultAsync(string Query, object userState) {
            if ((this.onBeginGetStringResultDelegate == null)) {
                this.onBeginGetStringResultDelegate = new BeginOperationDelegate(this.OnBeginGetStringResult);
            }
            if ((this.onEndGetStringResultDelegate == null)) {
                this.onEndGetStringResultDelegate = new EndOperationDelegate(this.OnEndGetStringResult);
            }
            if ((this.onGetStringResultCompletedDelegate == null)) {
                this.onGetStringResultCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStringResultCompleted);
            }
            base.InvokeAsync(this.onBeginGetStringResultDelegate, new object[] {
                        Query}, this.onEndGetStringResultDelegate, this.onGetStringResultCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NatuurApp.ServiceReference1.IService1.BeginExecuteCommand(string Query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExecuteCommand(Query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void NatuurApp.ServiceReference1.IService1.EndExecuteCommand(System.IAsyncResult result) {
            base.Channel.EndExecuteCommand(result);
        }
        
        private System.IAsyncResult OnBeginExecuteCommand(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Query = ((string)(inValues[0]));
            return ((NatuurApp.ServiceReference1.IService1)(this)).BeginExecuteCommand(Query, callback, asyncState);
        }
        
        private object[] OnEndExecuteCommand(System.IAsyncResult result) {
            ((NatuurApp.ServiceReference1.IService1)(this)).EndExecuteCommand(result);
            return null;
        }
        
        private void OnExecuteCommandCompleted(object state) {
            if ((this.ExecuteCommandCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExecuteCommandCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExecuteCommandAsync(string Query) {
            this.ExecuteCommandAsync(Query, null);
        }
        
        public void ExecuteCommandAsync(string Query, object userState) {
            if ((this.onBeginExecuteCommandDelegate == null)) {
                this.onBeginExecuteCommandDelegate = new BeginOperationDelegate(this.OnBeginExecuteCommand);
            }
            if ((this.onEndExecuteCommandDelegate == null)) {
                this.onEndExecuteCommandDelegate = new EndOperationDelegate(this.OnEndExecuteCommand);
            }
            if ((this.onExecuteCommandCompletedDelegate == null)) {
                this.onExecuteCommandCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExecuteCommandCompleted);
            }
            base.InvokeAsync(this.onBeginExecuteCommandDelegate, new object[] {
                        Query}, this.onEndExecuteCommandDelegate, this.onExecuteCommandCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NatuurApp.ServiceReference1.IService1.BeginGetDataTable(string Query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDataTable(Query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<object> NatuurApp.ServiceReference1.IService1.EndGetDataTable(System.IAsyncResult result) {
            return base.Channel.EndGetDataTable(result);
        }
        
        private System.IAsyncResult OnBeginGetDataTable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Query = ((string)(inValues[0]));
            return ((NatuurApp.ServiceReference1.IService1)(this)).BeginGetDataTable(Query, callback, asyncState);
        }
        
        private object[] OnEndGetDataTable(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<object> retVal = ((NatuurApp.ServiceReference1.IService1)(this)).EndGetDataTable(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataTableCompleted(object state) {
            if ((this.GetDataTableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataTableCompleted(this, new GetDataTableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataTableAsync(string Query) {
            this.GetDataTableAsync(Query, null);
        }
        
        public void GetDataTableAsync(string Query, object userState) {
            if ((this.onBeginGetDataTableDelegate == null)) {
                this.onBeginGetDataTableDelegate = new BeginOperationDelegate(this.OnBeginGetDataTable);
            }
            if ((this.onEndGetDataTableDelegate == null)) {
                this.onEndGetDataTableDelegate = new EndOperationDelegate(this.OnEndGetDataTable);
            }
            if ((this.onGetDataTableCompletedDelegate == null)) {
                this.onGetDataTableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataTableCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataTableDelegate, new object[] {
                        Query}, this.onEndGetDataTableDelegate, this.onGetDataTableCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override NatuurApp.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<NatuurApp.ServiceReference1.IService1>, NatuurApp.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<NatuurApp.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginTestDBConnection(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("TestDBConnection", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndTestDBConnection(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("TestDBConnection", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStringResult(string Query, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Query;
                System.IAsyncResult _result = base.BeginInvoke("GetStringResult", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetStringResult(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetStringResult", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginExecuteCommand(string Query, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Query;
                System.IAsyncResult _result = base.BeginInvoke("ExecuteCommand", _args, callback, asyncState);
                return _result;
            }
            
            public void EndExecuteCommand(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("ExecuteCommand", _args, result);
            }
            
            public System.IAsyncResult BeginGetDataTable(string Query, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Query;
                System.IAsyncResult _result = base.BeginInvoke("GetDataTable", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<object> EndGetDataTable(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<object> _result = ((System.Collections.ObjectModel.ObservableCollection<object>)(base.EndInvoke("GetDataTable", _args, result)));
                return _result;
            }
        }
    }
}
