//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace NatuurApp.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NatureArea", Namespace="http://schemas.datacontract.org/2004/07/DataClass")]
    public partial class NatureArea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int AreaIDField;
        
        private string AreaNameField;
        
        private string BestSeasonField;
        
        private string BriefDescriptionField;
        
        private string ExtendedDescriptionField;
        
        private string LatitudeField;
        
        private string LocationField;
        
        private string LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaID {
            get {
                return this.AreaIDField;
            }
            set {
                if ((this.AreaIDField.Equals(value) != true)) {
                    this.AreaIDField = value;
                    this.RaisePropertyChanged("AreaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaName {
            get {
                return this.AreaNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaNameField, value) != true)) {
                    this.AreaNameField = value;
                    this.RaisePropertyChanged("AreaName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BestSeason {
            get {
                return this.BestSeasonField;
            }
            set {
                if ((object.ReferenceEquals(this.BestSeasonField, value) != true)) {
                    this.BestSeasonField = value;
                    this.RaisePropertyChanged("BestSeason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BriefDescription {
            get {
                return this.BriefDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.BriefDescriptionField, value) != true)) {
                    this.BriefDescriptionField = value;
                    this.RaisePropertyChanged("BriefDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtendedDescription {
            get {
                return this.ExtendedDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedDescriptionField, value) != true)) {
                    this.ExtendedDescriptionField = value;
                    this.RaisePropertyChanged("ExtendedDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NatureAreaFoto", Namespace="http://schemas.datacontract.org/2004/07/DataClass")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NatuurApp.ServiceReference1.NatureArea))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<NatuurApp.ServiceReference1.NatureArea>))]
    public partial class NatureAreaFoto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int AreaIDField;
        
        private object Image1Field;
        
        private object Image2Field;
        
        private object Image3Field;
        
        private object Image4Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaID {
            get {
                return this.AreaIDField;
            }
            set {
                if ((this.AreaIDField.Equals(value) != true)) {
                    this.AreaIDField = value;
                    this.RaisePropertyChanged("AreaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Image1 {
            get {
                return this.Image1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image1Field, value) != true)) {
                    this.Image1Field = value;
                    this.RaisePropertyChanged("Image1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Image2 {
            get {
                return this.Image2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image2Field, value) != true)) {
                    this.Image2Field = value;
                    this.RaisePropertyChanged("Image2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Image3 {
            get {
                return this.Image3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image3Field, value) != true)) {
                    this.Image3Field = value;
                    this.RaisePropertyChanged("Image3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Image4 {
            get {
                return this.Image4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image4Field, value) != true)) {
                    this.Image4Field = value;
                    this.RaisePropertyChanged("Image4");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/TestDBConnection", ReplyAction="http://tempuri.org/IService1/TestDBConnectionResponse")]
        System.IAsyncResult BeginTestDBConnection(System.AsyncCallback callback, object asyncState);
        
        bool EndTestDBConnection(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetStringResult", ReplyAction="http://tempuri.org/IService1/GetStringResultResponse")]
        System.IAsyncResult BeginGetStringResult(string Query, System.AsyncCallback callback, object asyncState);
        
        string EndGetStringResult(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ExecuteCommand", ReplyAction="http://tempuri.org/IService1/ExecuteCommandResponse")]
        System.IAsyncResult BeginExecuteCommand(string Query, System.AsyncCallback callback, object asyncState);
        
        void EndExecuteCommand(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNatureAreaByID", ReplyAction="http://tempuri.org/IService1/GetNatureAreaByIDResponse")]
        System.IAsyncResult BeginGetNatureAreaByID(string AreaID, System.AsyncCallback callback, object asyncState);
        
        NatuurApp.ServiceReference1.NatureArea EndGetNatureAreaByID(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNatureAreas", ReplyAction="http://tempuri.org/IService1/GetNatureAreasResponse")]
        System.IAsyncResult BeginGetNatureAreas(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<NatuurApp.ServiceReference1.NatureArea> EndGetNatureAreas(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNatureAreaFotoByID", ReplyAction="http://tempuri.org/IService1/GetNatureAreaFotoByIDResponse")]
        System.IAsyncResult BeginGetNatureAreaFotoByID(string AreaID, System.AsyncCallback callback, object asyncState);
        
        NatuurApp.ServiceReference1.NatureAreaFoto EndGetNatureAreaFotoByID(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : NatuurApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestDBConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TestDBConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStringResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStringResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNatureAreaByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNatureAreaByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public NatuurApp.ServiceReference1.NatureArea Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((NatuurApp.ServiceReference1.NatureArea)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNatureAreasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNatureAreasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<NatuurApp.ServiceReference1.NatureArea> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<NatuurApp.ServiceReference1.NatureArea>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNatureAreaFotoByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNatureAreaFotoByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public NatuurApp.ServiceReference1.NatureAreaFoto Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((NatuurApp.ServiceReference1.NatureAreaFoto)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<NatuurApp.ServiceReference1.IService1>, NatuurApp.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginTestDBConnectionDelegate;
        
        private EndOperationDelegate onEndTestDBConnectionDelegate;
        
        private System.Threading.SendOrPostCallback onTestDBConnectionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStringResultDelegate;
        
        private EndOperationDelegate onEndGetStringResultDelegate;
        
        private System.Threading.SendOrPostCallback onGetStringResultCompletedDelegate;
        
        private BeginOperationDelegate onBeginExecuteCommandDelegate;
        
        private EndOperationDelegate onEndExecuteCommandDelegate;
        
        private System.Threading.SendOrPostCallback onExecuteCommandCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNatureAreaByIDDelegate;
        
        private EndOperationDelegate onEndGetNatureAreaByIDDelegate;
        
        private System.Threading.SendOrPostCallback onGetNatureAreaByIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNatureAreasDelegate;
        
        private EndOperationDelegate onEndGetNatureAreasDelegate;
        
        private System.Threading.SendOrPostCallback onGetNatureAreasCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNatureAreaFotoByIDDelegate;
        
        private EndOperationDelegate onEndGetNatureAreaFotoByIDDelegate;
        
        private System.Threading.SendOrPostCallback onGetNatureAreaFotoByIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<TestDBConnectionCompletedEventArgs> TestDBConnectionCompleted;
        
        public event System.EventHandler<GetStringResultCompletedEventArgs> GetStringResultCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ExecuteCommandCompleted;
        
        public event System.EventHandler<GetNatureAreaByIDCompletedEventArgs> GetNatureAreaByIDCompleted;
        
        public event System.EventHandler<GetNatureAreasCompletedEventArgs> GetNatureAreasCompleted;
        
        public event System.EventHandler<GetNatureAreaFotoByIDCompletedEventArgs> GetNatureAreaFotoByIDCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NatuurApp.ServiceReference1.IService1.BeginTestDBConnection(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTestDBConnection(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool NatuurApp.ServiceReference1.IService1.EndTestDBConnection(System.IAsyncResult result) {
            return base.Channel.EndTestDBConnection(result);
        }
        
        private System.IAsyncResult OnBeginTestDBConnection(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((NatuurApp.ServiceReference1.IService1)(this)).BeginTestDBConnection(callback, asyncState);
        }
        
        private object[] OnEndTestDBConnection(System.IAsyncResult result) {
            bool retVal = ((NatuurApp.ServiceReference1.IService1)(this)).EndTestDBConnection(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTestDBConnectionCompleted(object state) {
            if ((this.TestDBConnectionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TestDBConnectionCompleted(this, new TestDBConnectionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TestDBConnectionAsync() {
            this.TestDBConnectionAsync(null);
        }
        
        public void TestDBConnectionAsync(object userState) {
            if ((this.onBeginTestDBConnectionDelegate == null)) {
                this.onBeginTestDBConnectionDelegate = new BeginOperationDelegate(this.OnBeginTestDBConnection);
            }
            if ((this.onEndTestDBConnectionDelegate == null)) {
                this.onEndTestDBConnectionDelegate = new EndOperationDelegate(this.OnEndTestDBConnection);
            }
            if ((this.onTestDBConnectionCompletedDelegate == null)) {
                this.onTestDBConnectionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTestDBConnectionCompleted);
            }
            base.InvokeAsync(this.onBeginTestDBConnectionDelegate, null, this.onEndTestDBConnectionDelegate, this.onTestDBConnectionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NatuurApp.ServiceReference1.IService1.BeginGetStringResult(string Query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStringResult(Query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string NatuurApp.ServiceReference1.IService1.EndGetStringResult(System.IAsyncResult result) {
            return base.Channel.EndGetStringResult(result);
        }
        
        private System.IAsyncResult OnBeginGetStringResult(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Query = ((string)(inValues[0]));
            return ((NatuurApp.ServiceReference1.IService1)(this)).BeginGetStringResult(Query, callback, asyncState);
        }
        
        private object[] OnEndGetStringResult(System.IAsyncResult result) {
            string retVal = ((NatuurApp.ServiceReference1.IService1)(this)).EndGetStringResult(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStringResultCompleted(object state) {
            if ((this.GetStringResultCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStringResultCompleted(this, new GetStringResultCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStringResultAsync(string Query) {
            this.GetStringResultAsync(Query, null);
        }
        
        public void GetStringResultAsync(string Query, object userState) {
            if ((this.onBeginGetStringResultDelegate == null)) {
                this.onBeginGetStringResultDelegate = new BeginOperationDelegate(this.OnBeginGetStringResult);
            }
            if ((this.onEndGetStringResultDelegate == null)) {
                this.onEndGetStringResultDelegate = new EndOperationDelegate(this.OnEndGetStringResult);
            }
            if ((this.onGetStringResultCompletedDelegate == null)) {
                this.onGetStringResultCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStringResultCompleted);
            }
            base.InvokeAsync(this.onBeginGetStringResultDelegate, new object[] {
                        Query}, this.onEndGetStringResultDelegate, this.onGetStringResultCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NatuurApp.ServiceReference1.IService1.BeginExecuteCommand(string Query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExecuteCommand(Query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void NatuurApp.ServiceReference1.IService1.EndExecuteCommand(System.IAsyncResult result) {
            base.Channel.EndExecuteCommand(result);
        }
        
        private System.IAsyncResult OnBeginExecuteCommand(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Query = ((string)(inValues[0]));
            return ((NatuurApp.ServiceReference1.IService1)(this)).BeginExecuteCommand(Query, callback, asyncState);
        }
        
        private object[] OnEndExecuteCommand(System.IAsyncResult result) {
            ((NatuurApp.ServiceReference1.IService1)(this)).EndExecuteCommand(result);
            return null;
        }
        
        private void OnExecuteCommandCompleted(object state) {
            if ((this.ExecuteCommandCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExecuteCommandCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExecuteCommandAsync(string Query) {
            this.ExecuteCommandAsync(Query, null);
        }
        
        public void ExecuteCommandAsync(string Query, object userState) {
            if ((this.onBeginExecuteCommandDelegate == null)) {
                this.onBeginExecuteCommandDelegate = new BeginOperationDelegate(this.OnBeginExecuteCommand);
            }
            if ((this.onEndExecuteCommandDelegate == null)) {
                this.onEndExecuteCommandDelegate = new EndOperationDelegate(this.OnEndExecuteCommand);
            }
            if ((this.onExecuteCommandCompletedDelegate == null)) {
                this.onExecuteCommandCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExecuteCommandCompleted);
            }
            base.InvokeAsync(this.onBeginExecuteCommandDelegate, new object[] {
                        Query}, this.onEndExecuteCommandDelegate, this.onExecuteCommandCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NatuurApp.ServiceReference1.IService1.BeginGetNatureAreaByID(string AreaID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNatureAreaByID(AreaID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NatuurApp.ServiceReference1.NatureArea NatuurApp.ServiceReference1.IService1.EndGetNatureAreaByID(System.IAsyncResult result) {
            return base.Channel.EndGetNatureAreaByID(result);
        }
        
        private System.IAsyncResult OnBeginGetNatureAreaByID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string AreaID = ((string)(inValues[0]));
            return ((NatuurApp.ServiceReference1.IService1)(this)).BeginGetNatureAreaByID(AreaID, callback, asyncState);
        }
        
        private object[] OnEndGetNatureAreaByID(System.IAsyncResult result) {
            NatuurApp.ServiceReference1.NatureArea retVal = ((NatuurApp.ServiceReference1.IService1)(this)).EndGetNatureAreaByID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNatureAreaByIDCompleted(object state) {
            if ((this.GetNatureAreaByIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNatureAreaByIDCompleted(this, new GetNatureAreaByIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNatureAreaByIDAsync(string AreaID) {
            this.GetNatureAreaByIDAsync(AreaID, null);
        }
        
        public void GetNatureAreaByIDAsync(string AreaID, object userState) {
            if ((this.onBeginGetNatureAreaByIDDelegate == null)) {
                this.onBeginGetNatureAreaByIDDelegate = new BeginOperationDelegate(this.OnBeginGetNatureAreaByID);
            }
            if ((this.onEndGetNatureAreaByIDDelegate == null)) {
                this.onEndGetNatureAreaByIDDelegate = new EndOperationDelegate(this.OnEndGetNatureAreaByID);
            }
            if ((this.onGetNatureAreaByIDCompletedDelegate == null)) {
                this.onGetNatureAreaByIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNatureAreaByIDCompleted);
            }
            base.InvokeAsync(this.onBeginGetNatureAreaByIDDelegate, new object[] {
                        AreaID}, this.onEndGetNatureAreaByIDDelegate, this.onGetNatureAreaByIDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NatuurApp.ServiceReference1.IService1.BeginGetNatureAreas(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNatureAreas(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<NatuurApp.ServiceReference1.NatureArea> NatuurApp.ServiceReference1.IService1.EndGetNatureAreas(System.IAsyncResult result) {
            return base.Channel.EndGetNatureAreas(result);
        }
        
        private System.IAsyncResult OnBeginGetNatureAreas(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((NatuurApp.ServiceReference1.IService1)(this)).BeginGetNatureAreas(callback, asyncState);
        }
        
        private object[] OnEndGetNatureAreas(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<NatuurApp.ServiceReference1.NatureArea> retVal = ((NatuurApp.ServiceReference1.IService1)(this)).EndGetNatureAreas(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNatureAreasCompleted(object state) {
            if ((this.GetNatureAreasCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNatureAreasCompleted(this, new GetNatureAreasCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNatureAreasAsync() {
            this.GetNatureAreasAsync(null);
        }
        
        public void GetNatureAreasAsync(object userState) {
            if ((this.onBeginGetNatureAreasDelegate == null)) {
                this.onBeginGetNatureAreasDelegate = new BeginOperationDelegate(this.OnBeginGetNatureAreas);
            }
            if ((this.onEndGetNatureAreasDelegate == null)) {
                this.onEndGetNatureAreasDelegate = new EndOperationDelegate(this.OnEndGetNatureAreas);
            }
            if ((this.onGetNatureAreasCompletedDelegate == null)) {
                this.onGetNatureAreasCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNatureAreasCompleted);
            }
            base.InvokeAsync(this.onBeginGetNatureAreasDelegate, null, this.onEndGetNatureAreasDelegate, this.onGetNatureAreasCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NatuurApp.ServiceReference1.IService1.BeginGetNatureAreaFotoByID(string AreaID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNatureAreaFotoByID(AreaID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NatuurApp.ServiceReference1.NatureAreaFoto NatuurApp.ServiceReference1.IService1.EndGetNatureAreaFotoByID(System.IAsyncResult result) {
            return base.Channel.EndGetNatureAreaFotoByID(result);
        }
        
        private System.IAsyncResult OnBeginGetNatureAreaFotoByID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string AreaID = ((string)(inValues[0]));
            return ((NatuurApp.ServiceReference1.IService1)(this)).BeginGetNatureAreaFotoByID(AreaID, callback, asyncState);
        }
        
        private object[] OnEndGetNatureAreaFotoByID(System.IAsyncResult result) {
            NatuurApp.ServiceReference1.NatureAreaFoto retVal = ((NatuurApp.ServiceReference1.IService1)(this)).EndGetNatureAreaFotoByID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNatureAreaFotoByIDCompleted(object state) {
            if ((this.GetNatureAreaFotoByIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNatureAreaFotoByIDCompleted(this, new GetNatureAreaFotoByIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNatureAreaFotoByIDAsync(string AreaID) {
            this.GetNatureAreaFotoByIDAsync(AreaID, null);
        }
        
        public void GetNatureAreaFotoByIDAsync(string AreaID, object userState) {
            if ((this.onBeginGetNatureAreaFotoByIDDelegate == null)) {
                this.onBeginGetNatureAreaFotoByIDDelegate = new BeginOperationDelegate(this.OnBeginGetNatureAreaFotoByID);
            }
            if ((this.onEndGetNatureAreaFotoByIDDelegate == null)) {
                this.onEndGetNatureAreaFotoByIDDelegate = new EndOperationDelegate(this.OnEndGetNatureAreaFotoByID);
            }
            if ((this.onGetNatureAreaFotoByIDCompletedDelegate == null)) {
                this.onGetNatureAreaFotoByIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNatureAreaFotoByIDCompleted);
            }
            base.InvokeAsync(this.onBeginGetNatureAreaFotoByIDDelegate, new object[] {
                        AreaID}, this.onEndGetNatureAreaFotoByIDDelegate, this.onGetNatureAreaFotoByIDCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override NatuurApp.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<NatuurApp.ServiceReference1.IService1>, NatuurApp.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<NatuurApp.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginTestDBConnection(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("TestDBConnection", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndTestDBConnection(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("TestDBConnection", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStringResult(string Query, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Query;
                System.IAsyncResult _result = base.BeginInvoke("GetStringResult", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetStringResult(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetStringResult", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginExecuteCommand(string Query, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Query;
                System.IAsyncResult _result = base.BeginInvoke("ExecuteCommand", _args, callback, asyncState);
                return _result;
            }
            
            public void EndExecuteCommand(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("ExecuteCommand", _args, result);
            }
            
            public System.IAsyncResult BeginGetNatureAreaByID(string AreaID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = AreaID;
                System.IAsyncResult _result = base.BeginInvoke("GetNatureAreaByID", _args, callback, asyncState);
                return _result;
            }
            
            public NatuurApp.ServiceReference1.NatureArea EndGetNatureAreaByID(System.IAsyncResult result) {
                object[] _args = new object[0];
                NatuurApp.ServiceReference1.NatureArea _result = ((NatuurApp.ServiceReference1.NatureArea)(base.EndInvoke("GetNatureAreaByID", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetNatureAreas(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetNatureAreas", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<NatuurApp.ServiceReference1.NatureArea> EndGetNatureAreas(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<NatuurApp.ServiceReference1.NatureArea> _result = ((System.Collections.ObjectModel.ObservableCollection<NatuurApp.ServiceReference1.NatureArea>)(base.EndInvoke("GetNatureAreas", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetNatureAreaFotoByID(string AreaID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = AreaID;
                System.IAsyncResult _result = base.BeginInvoke("GetNatureAreaFotoByID", _args, callback, asyncState);
                return _result;
            }
            
            public NatuurApp.ServiceReference1.NatureAreaFoto EndGetNatureAreaFotoByID(System.IAsyncResult result) {
                object[] _args = new object[0];
                NatuurApp.ServiceReference1.NatureAreaFoto _result = ((NatuurApp.ServiceReference1.NatureAreaFoto)(base.EndInvoke("GetNatureAreaFotoByID", _args, result)));
                return _result;
            }
        }
    }
}
