//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.34011
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/GetData", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/GetData", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/GetDataResponse")]
    System.Threading.Tasks.Task<string> GetDataAsync(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/GetDataUsingDataContract", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/GetDataUsingDataContractResponse")]
    WcfService1.CompositeType GetDataUsingDataContract(WcfService1.CompositeType composite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/GetDataUsingDataContract", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/GetDataUsingDataContractResponse")]
    System.Threading.Tasks.Task<WcfService1.CompositeType> GetDataUsingDataContractAsync(WcfService1.CompositeType composite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/TestDBConnection", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/TestDBConnectionResponse")]
    bool TestDBConnection();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/TestDBConnection", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/TestDBConnectionResponse")]
    System.Threading.Tasks.Task<bool> TestDBConnectionAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/GetStringResult", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/GetStringResultResponse")]
    string GetStringResult(string Query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/GetStringResult", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/GetStringResultResponse")]
    System.Threading.Tasks.Task<string> GetStringResultAsync(string Query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/GetResult", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/GetResultResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfService1.CompositeType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    object[] GetResult(string Query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/GetResult", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/GetResultResponse")]
    System.Threading.Tasks.Task<object[]> GetResultAsync(string Query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/ExecuteCommand", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/ExecuteCommandResponse")]
    void ExecuteCommand(string Query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/ExecuteCommand", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/ExecuteCommandResponse")]
    System.Threading.Tasks.Task ExecuteCommandAsync(string Query);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public System.Threading.Tasks.Task<string> GetDataAsync(int value)
    {
        return base.Channel.GetDataAsync(value);
    }
    
    public WcfService1.CompositeType GetDataUsingDataContract(WcfService1.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }
    
    public System.Threading.Tasks.Task<WcfService1.CompositeType> GetDataUsingDataContractAsync(WcfService1.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContractAsync(composite);
    }
    
    public bool TestDBConnection()
    {
        return base.Channel.TestDBConnection();
    }
    
    public System.Threading.Tasks.Task<bool> TestDBConnectionAsync()
    {
        return base.Channel.TestDBConnectionAsync();
    }
    
    public string GetStringResult(string Query)
    {
        return base.Channel.GetStringResult(Query);
    }
    
    public System.Threading.Tasks.Task<string> GetStringResultAsync(string Query)
    {
        return base.Channel.GetStringResultAsync(Query);
    }
    
    public object[] GetResult(string Query)
    {
        return base.Channel.GetResult(Query);
    }
    
    public System.Threading.Tasks.Task<object[]> GetResultAsync(string Query)
    {
        return base.Channel.GetResultAsync(Query);
    }
    
    public void ExecuteCommand(string Query)
    {
        base.Channel.ExecuteCommand(Query);
    }
    
    public System.Threading.Tasks.Task ExecuteCommandAsync(string Query)
    {
        return base.Channel.ExecuteCommandAsync(Query);
    }
}
